baseURL = "http://joogps.me/blog/"
languageCode = "en-us"
title = "blog"

archetypeDir = "hugo/archetypes"
contentDir = "hugo/content"
data = "hugo/data"
layoutDir = "hugo/layouts"
resourcesDir = "hugo/resources"
staticDir = "hugo/static"
themesDir = "hugo/themes"

publishDir = "blog"

[taxonomies]
  tag = "tags"

# disqusShortname = "blog-ggfatrncjb"